### ISSUE TITLE
Tests do fail

### ISSUE THREAD

**Issue by fuyonet** [Awesome-Technologies/synapse-admin#2]
Dashmoard is loading without any login. 

Error: ENOENT: no such file or directory, stat '/var/www/synapse-admin/coverage/lcov-report/index.html'
test file:  
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                   |
----------|----------|----------|----------|----------|-------------------|

run test

     FAIL  tests/features/home/redux/login.test.js
      ● Test suite failed to run
        TypeError: Cannot read property 'cwd' of undefined
          
          at Object.getCacheKey (node_modules/babel-jest/build/index.js:153:51)
     FAIL  tests/Root.test.js
      ● Test suite failed to run
        TypeError: Cannot read property 'cwd' of undefined
          
          at Object.getCacheKey (node_modules/babel-jest/build/index.js:153:51)
     FAIL  tests/features/common/SidePanel.test.js
      ● Test suite failed to run
        TypeError: Cannot read property 'cwd' of undefined
          
          at Object.getCacheKey (node_modules/babel-jest/build/index.js:153:51)
     FAIL  tests/features/home/Login.test.js
      ● Test suite failed to run
        TypeError: Cannot read property 'cwd' of undefined
          
          at Object.getCacheKey (node_modules/babel-jest/build/index.js:153:51)
     FAIL  tests/features/common/PageNotFound.test.js
      ● Test suite failed to run
        TypeError: Cannot read property 'cwd' of undefined
          
          at Object.getCacheKey (node_modules/babel-jest/build/index.js:153:51)
     FAIL  tests/features/home/App.test.js
      ● Test suite failed to run
        TypeError: Cannot read property 'cwd' of undefined
          
          at Object.getCacheKey (node_modules/babel-jest/build/index.js:153:51)
     FAIL  tests/features/common/Layout.test.js
      ● Test suite failed to run
        TypeError: Cannot read property 'cwd' of undefined
          
          at Object.getCacheKey (node_modules/babel-jest/build/index.js:153:51)
     FAIL  tests/index.test.js
      ● Test suite failed to run
        TypeError: Cannot read property 'cwd' of undefined
          
          at Object.getCacheKey (node_modules/babel-jest/build/index.js:153:51)
    Test Suites: 8 failed, 8 total
    Tests:       0 total
    Snapshots:   0 total
    Time:        0.766s
    Ran all test suites.
        Failed to collect coverage from /var/www/synapse-admin/src/features/home/Login.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/home/App.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/home/redux/actions.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/home/redux/initialState.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/home/redux/constants.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/home/redux/reducer.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/home/redux/login.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/home/route.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/home/index.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/common/PageNotFound.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/common/SidePanel.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/common/redux/actions.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/common/redux/initialState.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/common/redux/constants.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/common/redux/reducer.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/common/route.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/common/index.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/features/common/Layout.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/Root.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/index.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/common/configStore.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/common/routeConfig.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/common/rootReducer.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
        Failed to collect coverage from /var/www/synapse-admin/src/common/history.js
        ERROR: TypeError: Cannot read property 'cwd' of undefined
        STACK: TypeError: Cannot read property 'cwd' of undefined
        at Object.getCacheKey (/var/www/synapse-admin/node_modules/babel-jest/build/index.js:153:51)
        at ScriptTransformer._getCacheKey (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
        at ScriptTransformer._getFileCachePath (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
        at ScriptTransformer.transformSource (/var/www/synapse-admin/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:32:59)
        at module.exports (/var/www/synapse-admin/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
        at /var/www/synapse-admin/node_modules/pify/index.js:29:7
        at new Promise ()
        at /var/www/synapse-admin/node_modules/pify/index.js:12:10
        at ret (/var/www/synapse-admin/node_modules/pify/index.js:56:34)
      
    ----------|----------|----------|----------|----------|-------------------|
    File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
    ----------|----------|----------|----------|----------|-------------------|
    All files |  Unknown |  Unknown |  Unknown |  Unknown |                   |
    ----------|----------|----------|----------|----------|-------------------|

i am not a developer ... dont know this code

**Comment by awesome-manuel** [comment]
Seems to be a problem with the test generated by `rekit`.

**Comment by awesome-manuel** [comment]
We did a complete rewrite using `react-admin`, now the tests are working properly.
