### ISSUE TITLE
Error when building and running with nodejs

### ISSUE THREAD

**Issue by Tropaion** [Awesome-Technologies/synapse-admin#277]
With ```yarn install``` I get following warning:
```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "react-admin > connected-react-router@6.9.2" has unmet peer dependency "history@^4.7.2".
warning "react-admin > react-final-form@6.5.7" has incorrect peer dependency "final-form@4.20.4".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > ra-test@3.19.4" has unmet peer dependency "ra-core@^3.13.0".
warning " > ra-test@3.19.4" has unmet peer dependency "react-redux@^7.1.0".
warning " > ra-test@3.19.4" has unmet peer dependency "react-router@^5.1.0".
warning " > ra-test@3.19.4" has unmet peer dependency "react-router-dom@^5.1.0".
warning " > ra-test@3.19.4" has unmet peer dependency "redux@^3.7.2 || ^4.0.3".
[4/4] Building fresh packages...
Done in 100.51s.
```
And yarn start throws error:
```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/opt/synapse-admin/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/opt/synapse-admin/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/opt/synapse-admin/node_modules/webpack/lib/NormalModule.js:471:10)
    at /opt/synapse-admin/node_modules/webpack/lib/NormalModule.js:503:5
    at /opt/synapse-admin/node_modules/webpack/lib/NormalModule.js:358:12
    at /opt/synapse-admin/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/opt/synapse-admin/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/opt/synapse-admin/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/opt/synapse-admin/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/opt/synapse-admin/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/opt/synapse-admin/node_modules/webpack/lib/NormalModule.js:417:16)
    at /opt/synapse-admin/node_modules/webpack/lib/NormalModule.js:452:10
    at /opt/synapse-admin/node_modules/webpack/lib/NormalModule.js:323:13
    at /opt/synapse-admin/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /opt/synapse-admin/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/opt/synapse-admin/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /opt/synapse-admin/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.7.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dklimpel** [comment]
I have made a test. The error occurs if you use Node v18. With Node v16 it works.

**Comment by dklimpel** [comment]
There is also a workaround. You have to set `export NODE_OPTIONS=--openssl-legacy-provider`

**Comment by dklimpel** [comment]
The reason is `react-scripts` / `webpack` v4. An update is needed:
```bash
yarn upgrade react-scripts@^5.0.0
yarn add eslint-config-react-app
```

**Comment by dklimpel** [comment]
I'm not sure if this should remain open? There is a PR needed for this update, to be ready for NodeJS v18 or v29.
